test: transform lower strip palindrome conway

transform:
	gcc -lm transform.c -o transform.out
	./transform.out

lower:
	gcc lower.c -o lower.out
	./lower.out

strip:
	gcc strip.c -o strip.out
	./strip.out

palindrome:
	gcc palindrome.c -o palindrome.out
	./palindrome.out

conway:
	gcc conway.c -o conway.out
	./conway.out

clean:
	rm *.out

.PHONY: transform lower strip palindrome conway clean
