test: uparrow collatz complex median pythagorean

uparrow:
	gcc uparrow.c -o uparrow.out
	./uparrow.out

collatz:
	gcc collatz.c -o collatz.out
	./collatz.out

complex:
	gcc complex.c -o complex.out
	./complex.out

median:
	gcc median.c -o median.out
	./median.out

pythagorean:
	gcc pythagorean.c -o pythagorean.out
	./pythagorean.out

clean:
	rm *.out

.PHONY: uparrow collatz complex median pythagorean test
