test: uparrow collatz mypow median pythagorean

uparrow:
	gcc uparrow.c -o uparrow.out
	./uparrow.out

collatz:
	gcc collatz.c -o collatz.out
	./collatz.out

mypow:
	gcc mypow.c -o mypow.out
	./mypow.out

median:
	gcc median.c -o median.out
	./median.out

pythagorean:
	gcc pythagorean.c -o pythagorean.out
	./pythagorean.out

clean:
	rm *.out

.PHONY: uparrow collatz mypow median pythagorean test
